import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';

@Injectable({
  providedIn: 'root'
})
export class PageService {

  apiUrl = environment.apiUrl;

  constructor(private http: HttpClient) { }

  getPage(pageName: string){
    return this.http.get(`${this.apiUrl}api/page/${pageName}`);
  }


  public privacyPage = `<p>This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use the Service and tells You about Your privacy rights and how the law protects You.</p>
                      <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                      <h1>Interpretation and Definitions</h1>
                      <h2>Interpretation</h2>
                      <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                      <h2>Definitions</h2>
                      <p>For the purposes of this Privacy Policy:</p>
                      <ul>
                      <li>
                      <p><strong>Account</strong>&nbsp;means a unique account created for You to access our Service or parts of our Service.</p>
                      </li>
                      <li>
                      <p><strong>Affiliate</strong>&nbsp;means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
                      </li>
                      <li>
                      <p><strong>Application</strong>&nbsp;means the software program provided by the Company downloaded by You on any electronic device, named Blogry</p>
                      </li>
                      <li>
                      <p><strong>Company</strong>&nbsp;(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to BLOGRY.</p>
                      </li>
                      <li>
                      <p><strong>Cookies</strong>&nbsp;are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                      </li>
                      <li>
                      <p><strong>Country</strong>&nbsp;refers to: Delhi, India</p>
                      </li>
                      <li>
                      <p><strong>Device</strong>&nbsp;means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                      </li>
                      <li>
                      <p><strong>Personal Data</strong>&nbsp;is any information that relates to an identified or identifiable individual.</p>
                      </li>
                      <li>
                      <p><strong>Service</strong>&nbsp;refers to the Application or the Website or both.</p>
                      </li>
                      <li>
                      <p><strong>Service Provider</strong>&nbsp;means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                      </li>
                      <li>
                      <p><strong>Third-party Social Media Service</strong>&nbsp;refers to any website or any social network website through which a User can log in or create an account to use the Service.</p>
                      </li>
                      <li>
                      <p><strong>Usage Data</strong>&nbsp;refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                      </li>
                      <li>
                      <p><strong>Website</strong>&nbsp;refers to BLOGRY, accessible from&nbsp;<span style="text-decoration: underline;"><a href="https://www.blogry.co/" target="_blank" rel="noopener" aria-invalid="true">https://www.blogry.co</a></span></p>
                      </li>
                      <li>
                      <p><strong>You</strong>&nbsp;means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                      </li>
                      </ul>
                      <h1>Collecting and Using Your Personal Data</h1>
                      <h2>Types of Data Collected</h2>
                      <h3>Personal Data</h3>
                      <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                      <ul>
                      <li>
                      <p>Email address</p>
                      </li>
                      <li>
                      <p>First name and last name</p>
                      </li>
                      <li>
                      <p>Phone number</p>
                      </li>
                      <li>
                      <p>Address, State, Province, ZIP/Postal code, City</p>
                      </li>
                      <li>
                      <p>Usage Data</p>
                      </li>
                      <li>
                      <p>Bank details or any other payment method through which we can transfer money into your bank account</p>
                      </li>
                      </ul>
                      <h3>Usage Data</h3>
                      <p>Usage Data is collected automatically when using the Service.</p>
                      <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                      <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                      <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
                      <h3>Information from Third-Party Social Media Services</h3>
                      <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
                      <ul>
                      <li>
                      <p>Google</p>
                      </li>
                      <li>
                      <p>Facebook</p>
                      </li>
                      </ul>
                      <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
                      <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
                      <h3>Information Collected while Using the Application</h3>
                      <p>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
                      <ul>
                      <li>
                      <p>Information regarding your location</p>
                      </li>
                      <li>
                      <p>Pictures and other information from your Device's camera and photo library</p>
                      </li>
                      </ul>
                      <p>We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.</p>
                      <p>You can enable or disable access to this information at any time, through Your Device settings.</p>
                      <h3>Tracking Technologies and Cookies</h3>
                      <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                      <ul>
                      <li>
                      <p><strong>Cookies or Browser Cookies.</strong>&nbsp;A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</p>
                      </li>
                      <li>
                      <p><strong>Flash Cookies.</strong>&nbsp;Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read "Where can I change the settings for disabling, or deleting local shared objects?" available at&nbsp;<span style="text-decoration: underline;"><a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_" target="_blank" rel="noopener">https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</a></span></p>
                      </li>
                      <li>
                      <p><strong>Web Beacons.</strong>&nbsp;Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</p>
                      </li>
                      </ul>
                      <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
                      <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
                      <ul>
                      <li>
                      <p><strong>Necessary / Essential Cookies</strong></p>
                      </li>
                      </ul>
                      <p>Type: Session Cookies</p>
                      <p>Administered by: Us</p>
                      <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                      <ul>
                      <li>
                      <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                      </li>
                      </ul>
                      <p>Type: Persistent Cookies</p>
                      <p>Administered by: Us</p>
                      <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                      <ul>
                      <li>
                      <p><strong>Functionality Cookies</strong></p>
                      </li>
                      </ul>
                      <p>Type: Persistent Cookies</p>
                      <p>Administered by: Us</p>
                      <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                      <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
                      <h2>Use of Your Personal Data</h2>
                      <p>The Company may use Personal Data for the following purposes:</p>
                      <ul>
                      <li>
                      <p><strong>To provide and maintain our Service</strong>: Including to monitor the usage of our Service.</p>
                      </li>
                      <li>
                      <p><strong>To manage Your Account:</strong>&nbsp;to manage your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
                      </li>
                      <li>
                      <p><strong>For the performance of a contract:</strong>&nbsp;the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
                      </li>
                      <li>
                      <p><strong>To contact You:</strong>&nbsp;To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
                      </li>
                      <li>
                      <p><strong>To provide You</strong>&nbsp;with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>
                      </li>
                      <li>
                      <p><strong>To manage Your requests:</strong>&nbsp;To attend and manage Your requests to Us.</p>
                      </li>
                      <li>
                      <p><strong>For business transfers:</strong>&nbsp;We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
                      </li>
                      <li>
                      <p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
                      </li>
                      </ul>
                      <p>We may share Your personal information in the following situations:</p>
                      <ul>
                      <li>
                      <p><strong>With Service Providers:</strong>&nbsp;We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</p>
                      </li>
                      <li>
                      <p><strong>For business transfers:</strong>&nbsp;We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</p>
                      </li>
                      <li>
                      <p><strong>With Affiliates:</strong>&nbsp;We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</p>
                      </li>
                      <li>
                      <p><strong>With business partners:</strong>&nbsp;We may share Your information with Our business partners to offer You certain products, services or promotions.</p>
                      </li>
                      <li>
                      <p><strong>With other users:</strong>&nbsp;when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</p>
                      </li>
                      <li>
                      <p><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</p>
                      </li>
                      </ul>
                      <h2>Retention of Your Personal Data</h2>
                      <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                      <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
                      <h2>Transfer of Your Personal Data</h2>
                      <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to &mdash; and maintained on &mdash; computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
                      <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                      <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
                      <h2>Disclosure of Your Personal Data</h2>
                      <h3>Business Transactions</h3>
                      <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                      <h3>Law enforcement</h3>
                      <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                      <h3>Other legal requirements</h3>
                      <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                      <ul>
                      <li>
                      <p>Comply with a legal obligation</p>
                      </li>
                      <li>
                      <p>Protect and defend the rights or property of the Company</p>
                      </li>
                      <li>
                      <p>Prevent or investigate possible wrongdoing in connection with the Service</p>
                      </li>
                      <li>
                      <p>Protect the personal safety of Users of the Service or the public</p>
                      </li>
                      <li>
                      <p>Protect against legal liability</p>
                      </li>
                      </ul>
                      <h2>Security of Your Personal Data</h2>
                      <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                      <h1>Children's Privacy</h1>
                      <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                      <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
                      <h1>Links to Other Websites</h1>
                      <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                      <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                      <h1>Changes to this Privacy Policy</h1>
                      <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                      <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
                      <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                      <h1>Contact Us</h1>
                      <p>If you have any questions about this Privacy Policy, You can contact us:</p>`;
  public termPage = `<p>PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY, AS IT CONTAINS IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS AND REMEDIES.</p>
                    <h3>&nbsp;</h3>
                    <h3>1. OVERVIEW</h3>
                    <p>This Terms of Service Agreement ("Agreement") is entered into by and between Blogry, and is made effective as of the date of your use of this website <a href="https://www.blogry.co" aria-invalid="true">https://www.blogry.co</a> ("Site") or the date of electronic acceptance.</p>
                    <p>This Agreement sets forth the general terms and conditions of your use of the <a href="https://www.blogry.co" aria-invalid="true">https://www.blogry.co</a> as well as the products and/or services purchased or accessed through this Site (the "Services").Whether you are simply browsing or using this Site or purchase Services, your use of this Site and your electronic acceptance of this Agreement signifies that you have read, understand, acknowledge and agree to be bound by this Agreement our&nbsp;privacy policy. The terms "we", "us" or "our" shall refer to Company. The terms "you", "your", "User" or "customer" shall refer to any individual or entity who accepts this Agreement, uses our Site, has access or uses the Services. Nothing in this Agreement shall be deemed to confer any third-party rights or benefits.</p>
                    <p>Company may, in its sole and absolute discretion, change or modify this Agreement, and any policies or agreements which are incorporated herein, at any time, and such changes or modifications shall be effective immediately upon posting to this Site. Your use of this Site or the Services after such changes or modifications have been made shall constitute your acceptance of this Agreement as last revised.</p>
                    <p>IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT AS LAST REVISED, DO NOT USE (OR CONTINUE TO USE) THIS SITE OR THE SERVICES.</p>
                    <h3>2. ELIGIBILITY</h3>
                    <p>This Site and the Services are available only to Users who can form legally binding contracts under applicable law. By using this Site or the Services, you represent and warrant that you are (i) at least eighteen (18) years of age, (ii) otherwise recognized as being able to form legally binding contracts under applicable law, and (iii) are not a person barred from purchasing or receiving the Services found under the laws of the India or other applicable jurisdiction.</p>
                    <p>If you are entering into this Agreement on behalf of a company or any corporate entity, you represent and warrant that you have the legal authority to bind such corporate entity to the terms and conditions contained in this Agreement, in which case the terms "you", "your", "User" or "customer" shall refer to such corporate entity. If, after your electronic acceptance of this Agreement, Company finds that you do not have the legal authority to bind such corporate entity, you will be personally responsible for the obligations contained in this Agreement.</p>
                    <h3>3. RULES OF USER CONDUCT</h3>
                    <p>By using this Site You acknowledge and agree that:</p>
                    <ul>
                    <li>
                    <p>Your use of this Site, including any content you submit, will comply with this Agreement and all applicable local, state, national and international laws, rules and regulations.</p>
                    </li>
                    </ul>
                    <p>You will not use this Site in a manner that:</p>
                    <ul>
                    <li>
                    <p>Is illegal, or promotes or encourages illegal activity;</p>
                    </li>
                    <li>
                    <p>Promotes, encourages or engages in child pornography or the exploitation of children;</p>
                    </li>
                    <li>
                    <p>Promotes, encourages or engages in terrorism, violence against people, animals, or property;</p>
                    </li>
                    <li>
                    <p>Promotes, encourages or engages in any spam or other unsolicited bulk email, or computer or network hacking or cracking;</p>
                    </li>
                    <li>
                    <p>Infringes on the intellectual property rights of another User or any other person or entity;</p>
                    </li>
                    <li>
                    <p>Violates the privacy or publicity rights of another User or any other person or entity, or breaches any duty of confidentiality that you owe to another User or any other person or entity;</p>
                    </li>
                    <li>
                    <p>Interferes with the operation of this Site;</p>
                    </li>
                    <li>
                    <p>Contains or installs any viruses, worms, bugs, Trojan horses, Cryptocurrency Miners or other code, files or programs designed to, or capable of, using many resources, disrupting, damaging, or limiting the functionality of any software or hardware.</p>
                    </li>
                    </ul>
                    <p>You will not:</p>
                    <ul>
                    <li>
                    <p>copy or distribute in any Blogry any part of this Site, except where expressly authorized by Company,</p>
                    </li>
                    <li>
                    <p>copy or duplicate this Terms of Services agreement,</p>
                    </li>
                    <li>
                    <p>modify or alter any part of this Site or any of its related technologies,</p>
                    </li>
                    <li>
                    <p>access Companies Content (as defined below) or User Content through any technology or means other than through this Site itself.</p>
                    </li>
                    </ul>
                    <h3>4. INTELLECTUAL PROPERTY</h3>
                    <p>In addition to the general rules above, the provisions in this Section apply specifically to your use of Companies Content posted to Site. Companies Content on this Site, including without limitation the text, software, scripts, source code, API, graphics, photos, sounds, music, videos and interactive features and the trademarks, service marks and logos contained therein ("Companies Content"), are owned by or licensed to Blogry in perpetuity, and are subject to copyright, trademark, and/or patent protection.</p>
                    <p>Companies Content is provided to you "as is", "as available" and "with all faults" for your information and personal, non-commercial use only and may not be downloaded, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any purposes whatsoever without the express prior written consent of Company. No right or license under any copyright, trademark, patent, or other proprietary right or license is granted by this Agreement.</p>
                    <h3>5. YOUR USE OF USER CONTENT</h3>
                    <p>Some of the features of this Site may allow Users to view, post, publish, share, or manage (a) ideas, opinions, recommendations, or advice ("User Submissions"), or (b) literary, artistic, musical, or other content, including but not limited to photos and videos (together with User Submissions, "User Content"). By posting or publishing User Content to this Site, you represent and warrant to Company that (i) you have all necessary rights to distribute User Content via this Site or via the Services, either because you are the author of the User Content and have the right to distribute the same, or because you have the appropriate distribution rights, licenses, consents, and/or permissions to use, in writing, from the copyright or other owner of the User Content, and (ii) the User Content does not violate the rights of any third party.</p>
                    <p>You agree not to circumvent, disable or otherwise interfere with the security-related features of this Site (including without limitation those features that prevent or restrict use or copying of any Companies Content or User Content) or enforce limitations on the use of this Site, the Companies Content or the User Content therein.</p>
                    <h3>6. COMPANIES USE OF USER CONTENT</h3>
                    <p>The provisions in this Section apply specifically to Companies use of User Content posted to Site.</p>
                    <p>You shall be solely responsible for any and all of your User Content or User Content that is submitted by you, and the consequences of, and requirements for, distributing it.</p>
                    <p>With Respect to User Submissions, you acknowledge and agree that:</p>
                    <ul>
                    <li>
                    <p>Your User Submissions are entirely voluntary.</p>
                    </li>
                    <li>
                    <p>Your User Submissions do not establish a confidential relationship or obligate Company to treat your User Submissions as confidential or secret.</p>
                    </li>
                    <li>
                    <p>Company has no obligation, either express or implied, to develop or use your User Submissions, and no compensation is due to you or to anyone else for any intentional or unintentional use of your User Submissions.</p>
                    </li>
                    </ul>
                    <p>Company shall own exclusive rights (including all intellectual property and other proprietary rights) to any User Submissions posted to this Site, and shall be entitled to the unrestricted use and dissemination of any User Submissions posted to this Site for any purpose, commercial or otherwise, without acknowledgment or compensation to you or to anyone else.</p>
                    <p>With Respect to User Content, by posting or publishing User Content to this Site, you authorize Company to use the intellectual property and other proprietary rights in and to your User Content to enable inclusion and use of the User Content in the manner contemplated by this Site and this Agreement.</p>
                    <p>You hereby grant Company a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to use, reproduce, distribute, prepare derivative works of, combine with other works, display, and perform your User Content in connection with this Site, including without limitation for promoting and redistributing all or part of this Site in any media formats and through any media channels without restrictions of any kind and without payment or other consideration of any kind, or permission or notification, to you or any third party. You also hereby grant each User of this Site a non-exclusive license to access your User Content through this Site, and to use, reproduce, distribute, prepare derivative works of, combine with other works, display, and perform your User Content as permitted through the functionality of this Site and under this Agreement.</p>
                    <p>The above licenses granted by you in your User Content terminate within a commercially reasonable time after you remove or delete your User Content from this Site. You understand and agree, however, that Company may retain (but not distribute, display, or perform) server copies of your User Content that have been removed or deleted. The above licenses granted by you in your User Content are perpetual and irrevocable.</p>
                    <p>Company generally does not pre-screen User Content but reserves the right (but undertakes no duty) to do so and decide whether any item of User Content is appropriate and/or complies with this Agreement. Company may remove any item of User Content if it violating this Agreement, at any time and without prior notice.</p>
                    <h3>7. LINKS TO THIRD-PARTY WEBSITES</h3>
                    <p>This Site may contain links to third-party websites that are not owned or controlled by Company. Company assumes no responsibility for the content, terms and conditions, privacy policies, or practices of any third-party websites. In addition, Company does not censor or edit the content of any third-party websites. By using this Site you expressly release Company from any and all liability arising from your use of any third-party website. Accordingly, Company encourages you to be aware when you leave this Site and to review the terms and conditions, privacy policies, and other governing documents of each other website that you may visit.</p>
                    <h3>8. DISCLAIMER OF REPRESENTATIONS AND WARRANTIES</h3>
                    <p>YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT YOUR USE OF THIS SITE SHALL BE AT YOUR OWN RISK AND THAT THIS SITE ARE PROVIDED "AS IS", "AS AVAILABLE" AND "WITH ALL FAULTS". COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, DISCLAIM ALL WARRANTIES, STATUTORY, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS MAKE NO REPRESENTATIONS OR WARRANTIES ABOUT (I) THE ACCURACY, COMPLETENESS, OR CONTENT OF THIS SITE, (II) THE ACCURACY, COMPLETENESS, OR CONTENT OF ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, AND/OR (III) THE SERVICES FOUND AT THIS SITE OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, AND COMPANY ASSUMES NO LIABILITY OR RESPONSIBILITY FOR THE SAME.</p>
                    <p>IN ADDITION, YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT NO ORAL OR WRITTEN INFORMATION OR ADVICE PROVIDED BY COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, AND THIRD-PARTY SERVICE PROVIDERS WILL (I) CONSTITUTE LEGAL OR FINANCIAL ADVICE OR (II) CREATE A WARRANTY OF ANY KIND WITH RESPECT TO THIS SITE OR THE SERVICES FOUND AT THIS SITE, AND USERS SHOULD NOT RELY ON ANY SUCH INFORMATION OR ADVICE.</p>
                    <p>THE FOREGOING DISCLAIMER OF REPRESENTATIONS AND WARRANTIES SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW, and shall survive any termination or expiration of this Agreement or your use of this Site or the Services found at this Site.</p>
                    <h3>9. LIMITATION OF LIABILITY</h3>
                    <p>IN NO EVENT SHALL COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND ALL THIRD PARTY SERVICE PROVIDERS, BE LIABLE TO YOU OR ANY OTHER PERSON OR ENTITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING ANY DAMAGES THAT MAY RESULT FROM (I) THE ACCURACY, COMPLETENESS, OR CONTENT OF THIS SITE, (II) THE ACCURACY, COMPLETENESS, OR CONTENT OF ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (III) THE SERVICES FOUND AT THIS SITE OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (IV) PERSONAL INJURY OR PROPERTY DAMAGE OF ANY NATURE WHATSOEVER, (V) THIRD-PARTY CONDUCT OF ANY NATURE WHATSOEVER, (VI) ANY INTERRUPTION OR CESSATION OF SERVICES TO OR FROM THIS SITE OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (VII) ANY VIRUSES, WORMS, BUGS, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR FROM THIS SITE OR ANY SITES LINKED (THROUGH HYPERLINKS, BANNER ADVERTISING OR OTHERWISE) TO THIS SITE, (VIII) ANY USER CONTENT OR CONTENT THAT IS DEFAMATORY, HARASSING, ABUSIVE, HARMFUL TO MINORS OR ANY PROTECTED CLASS, PORNOGRAPHIC, "X-RATED", OBSCENE OR OTHERWISE OBJECTIONABLE, AND/OR (IX) ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF THIS SITE OR THE SERVICES FOUND AT THIS SITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL OR EQUITABLE THEORY, AND WHETHER OR NOT COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                    <p>IN ADDITION, You SPECIFICALLY ACKNOWLEDGE AND agree that any cause of action arising out of or related to this Site or the Services found at this Site must be commenced within one (1) year after the cause of action accrues, otherwise such cause of action shall be permanently barred.</p>
                    <p>THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW, AND shall survive any termination or expiration of this Agreement or your use of this Site or the Services found at this Site.</p>
                    <h3>10. INDEMNITY</h3>
                    <p>You agree to protect, defend, indemnify and hold harmless Company and its officers, directors, employees, agents from and against any and all claims, demands, costs, expenses, losses, liabilities and damages of every kind and nature (including, without limitation, reasonable attorneys&rsquo; fees) imposed upon or incurred by Company directly or indirectly arising from (i) your use of and access to this Site; (ii) your violation of any provision of this Agreement or the policies or agreements which are incorporated herein; and/or (iii) your violation of any third-party right, including without limitation any intellectual property or other proprietary right. The indemnification obligations under this section shall survive any termination or expiration of this Agreement or your use of this Site or the Services found at this Site.</p>
                    <h3>11. DATA TRANSFER</h3>
                    <p>If you are visiting this Site from a country other than the country in which our servers are located, your communications with us may result in the transfer of information across international boundaries. By visiting this Site and communicating electronically with us, you consent to such transfers.</p>
                    <h3>12. AVAILABILITY OF WEBSITE</h3>
                    <p>Subject to the terms and conditions of this Agreement and our policies, we shall use commercially reasonable efforts to attempt to provide this Site on 24/7 basis. You acknowledge and agree that from time to time this Site may be inaccessible for any reason including, but not limited to, periodic maintenance, repairs or replacements that we undertake from time to time, or other causes beyond our control including, but not limited to, interruption or failure of telecommunication or digital transmission links or other failures.</p>
                    <p>You acknowledge and agree that we have no control over the availability of this Site on a continuous or uninterrupted basis, and that we assume no liability to you or any other party with regard thereto.</p>
                    <h3>13. DISCONTINUED SERVICES</h3>
                    <p>Company reserves the right to cease offering or providing any of the Services at any time, for any or no reason, and without prior notice. Although Company makes great effort to maximize the lifespan of all its Services, there are times when a Service we offer will be discontinued. If that is the case, that product or service will no longer be supported by Company. In such case, Company will either offer a comparable Service for you to migrate to or a refund. Company will not be liable to you or any third party for any modification, suspension, or discontinuance of any of the Services we may offer or facilitate access to.</p>
                    <h3>14. FEES AND PAYMENTS</h3>
                    <p>You acknowledge and agree that your payment will be charged and processed by Blogry.</p>
                    <p>You agree to pay any and all prices and fees due for Services purchased or obtained at this Site at the time you order the Services.</p>
                    <p>Company expressly reserves the right to change or modify its prices and fees at any time, and such changes or modifications shall be posted online at this Site and effective immediately without need for further notice to you.</p>
                    <p>Except as expressly provided in these Terms, all charges and payments are non-refundable, non-cancellable, and non-creditable, even if your Services are suspended, terminated, or transferred prior to the end of the Services term.</p>
                    <h3>15. NO THIRD-PARTY BENEFICIARIES</h3>
                    <p>Nothing in this Agreement shall be deemed to confer any third-party rights or benefits.</p>
                    <h3>16. COMPLIANCE WITH LOCAL LAWS</h3>
                    <p>Company makes no representation or warranty that the content available on this Site are appropriate in every country or jurisdiction, and access to this Site from countries or jurisdictions where its content is illegal is prohibited. Users who choose to access this Site are responsible for compliance with all local laws, rules and regulations.</p>
                    <h3>17. GOVERNING LAW</h3>
                    <p>This Agreement and any dispute or claim arising out of or in connection with it or its subject matter or formation shall be governed by and construed in accordance with the laws of India, delhi, to the exclusion of conflict of law rules.</p>
                    <h3>18. DISPUTE RESOLUTION</h3>
                    <p>Any controversy or claim arising out of or relating to these Terms of Services will be settled by binding arbitration. Any such controversy or claim must be arbitrated on an individual basis, and must not be consolidated in any arbitration with any claim or controversy of any other party. The arbitration must be conducted in India, delhi, and judgment on the arbitration award may be entered into any court having jurisdiction thereof.</p>
                    <h3>19. TITLES AND HEADINGS</h3>
                    <p>The titles and headings of this Agreement are for convenience and ease of reference only and shall not be utilized in any way to construe or interpret the agreement of the parties as otherwise set forth herein.</p>
                    <h3>20. SEVERABILITY</h3>
                    <p>Each covenant and agreement in this Agreement shall be construed for all purposes to be a separate and independent covenant or agreement. If a court of competent jurisdiction holds any provision (or portion of a provision) of this Agreement to be illegal, invalid, or otherwise unenforceable, the remaining provisions (or portions of provisions) of this Agreement shall not be affected thereby and shall be found to be valid and enforceable to the fullest extent permitted by law.</p>
                    <h3>21. CONTACT INFORMATION</h3>
                    <p>If you have any questions about this Agreement, please contact us by email at the following address:</p>
                    <p>blogry.info@gmail.com</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <p><span style="text-decoration: underline;">ADS POLICY</span></p>
                    <p>&nbsp;</p>
                    <p>Advertisers must follow our advertising policy to run BLOGRY ADS.&nbsp;</p>
                    <p>When advertisers publish advertisements, every advertisement is reviewed keeping these policies in mind.</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <p>1. HOW WE REVIEW YOUR ADS?</p>
                    <p>&nbsp;</p>
                    <p>The ads will be first reviewed by the Ads Team and then you will be able to run your ads on blogry.</p>
                    <p>&nbsp;</p>
                    <p>2. WHAT ADS TEAM CHECK BEFORE APPROVING YOUR ADS?</p>
                    <p>&nbsp;</p>
                    <p>Firstly we will check the content that you have written in your blog.</p>
                    <p>You can check the content policy to see what type of content you can write.</p>
                    <p>Then we will check the link that you have used in your ads that it is working properly or not or the link promote good content or not.</p>
                    <p>&nbsp;</p>
                    <p>After this procedure a mail will be send to you via your email or a message on your registered mobile number depending on the information that you have provided us, that your ad is approved or rejected.</p>
                    <p>&nbsp;</p>
                    <p><span style="text-decoration: underline;">EARNING POLICY</span></p>
                    <p>&nbsp;</p>
                    <p>The only way through which you can earn from Blogry is by clicks on the blogry ads that will be placed on your blog. Per click on the ads you will earn around RS.2-4 based on the quality and length of your blog</p>
                    <p>&nbsp;</p>
                    <p><a name="_GoBack"></a> CONTENT POLICY</p>
                    <p>&nbsp;</p>
                    <p><strong><br /></strong>We don't permit content that compromise, energize, or actuate viciousness against anybody, straightforwardly or by implication.</p>
                    <p><strong><br /></strong>We don't permit content that comprises or advances savagery, badgering, or scorn against individuals dependent on attributes like race, nationality, public beginning, religion, standing, inability, infection, age, sexual direction, sex, or sex character.</p>
                    <p>&nbsp;</p>
                    <p>We don't permit posts or records that commend, celebrate, minimize, or downplay brutality, enduring, misuse, or passings of people or gatherings. This incorporates the utilization of logical or pseudoscientific cases or deceiving insights to pathologize, dehumanize, or weaken others. We don't permit calls for narrow mindedness, prohibition, or isolation dependent on secured qualities, nor do we permit the glorification of gatherings which do any of the abovementioned.</p>
                    <p>We don't permit scornful content, pictures, images, or other substance, remembering for your username, profile, or bio.</p>
                    <p><strong><br /></strong><br /><br /></p>
                    <p>We don't permit harassing, undermining, taunting, or disgracing somebody, or presenting things probably on urge others to do as such.</p>
                    <p><br /><br /></p>
                    <p>&bull; We don't permit participating in a dull or focused on mission of badgering against somebody or a gathering of individuals</p>
                    <p><br /><br /></p>
                    <p>&bull; We don't permit utilizing injurious language, racial slurs, or indecencies to criticize or assault somebody or a gathering of individuals</p>
                    <p><br /><br /></p>
                    <p>&bull; We don't permit utilizing Blogry includes such that endeavors to or pesters or badger somebody, or to cause inorganic to notice your substance on Blogry.</p>
                    <p><br /><br /></p>
                    <p>&bull; We don't permit investigating organizations or items in a needlessly unsafe or oppressive way</p>
                    <p><br /><br /></p>
                    <p>&bull; We don't permit posting pictures of, records of, duplicates of, or connections to private interchanges between private people without the unequivocal assent, everything being equal, to the correspondence. Redacting names or other data doesn't override the need to get consents</p>
                    <p><br /><br /></p>
                    <p>&bull; We don't permit doxing, which incorporates private or dark individual data as well as the total of openly accessible data to target, disgrace, coercion, badger, scare, compromise, or imperil an individual or gathering of individuals</p>
                    <p><br /><br /></p>
                    <p>&bull; We don't permit posting close or unequivocal pictures taken or posted without the subject's express assent</p>
                    <p><br /><br /></p>
                    <p>&bull; We don't permit content that abuses others' protection or individual wellbeing, including touchy or secret data, for example, Mastercard numbers, government backed retirement numbers, non-public telephone numbers, actual addresses, email addresses, or other comparable data.</p>
                    <p>We don't permit promotion of questionable, suspect, or outrageous substance.</p>
                    <p>We don't permit assistance of betting or wagering</p>
                    <p>We don't permit assistance of purchasing or selling web-based media communications, including off-stage</p>
                    <p>We don't permit assistance of sexual administrations</p>
                    <p>We don't permit assistance of copyright or other protected innovation infringement</p>
                    <p>We don't permit assistance or proof of abusing the terms of administration of Blogry or third party(s)</p>
                    <p>We don't permit help of illicit hacking (e.g., taking accreditations, bargaining individual information)</p>
                    <p>We don't permit the utilization of pseudoscience, disinformation, or other substance that is in opposition to general wellbeing or security</p>
                    <p><br /><br /></p>
                    <p>We don't permit substance or records that take part in on-stage, off-stage, or cross-stage missions of focusing on, badgering, disdain discourse, viciousness, or disinformation. We may consider off-stage activities in surveying a BLOGRY account, and confine access or accessibility to that record.</p>
                    <p><br /><br /></p>
                    <p>We don't permit posting, connecting to, or in any case advancing obscene pictures or recordings. We do permit suggestive composition and non-realistic sexual pictures.</p>
                    <p><br /><br /></p>
                    <p>We don't permit needlessly realistic or upsetting media, paying little heed to topic.</p>
                    <p><br /><br /></p>
                    <p>We don't permit content advancing the sexual, vicious, or other abuse of minors, including the sexualization of anecdotal minors.</p>
                    <p><br /><br /></p>
                    <p>We don't permit substance or exercises that support, advance or celebrate demonstrations of self-hurt, like cutting, dietary issues like anorexia or bulimia, and self destruction. On the off chance that you experience clients thinking about or undermining self-hurt, if it's not too much trouble, report it to us through the report button put on the blog or email address connected beneath.</p>
                    <p><br /><br /></p>
                    <p>We don't permit posting copy duplicates of a similar substance to Blogry, regardless of whether from a solitary record or across different records, either freely or as an unlisted story. (You are permitted to cross-post substance from your blog to Blogry, if you own the rights for the substance.)</p>
                    <p><br /><br /></p>
                    <p>We don't permit spam or abuse of Blogry. All spam or abuse will be quickly taken out from Blogry without warning. Instances of spam or abuse include:</p>
                    <p><br /><br /></p>
                    <p>&bull; Scraping and reposting content from different hotspots for the main role of producing income or other individual increases</p>
                    <p><br /><br /></p>
                    <p>&bull; Posting copy content, regardless of whether from a solitary record or across different records</p>
                    <p><br /><br /></p>
                    <p>&bull; Blogs where the substance is cut determined to connection to the remainder of the article on an alternate site</p>
                    <p><br /><br /></p>
                    <p>&bull; Performing a lopsidedly huge number of connections, especially via mechanized methods. This incorporates mass or aimless connections, like after of different records (follow spam) applauding, featuring, or leaving notes</p>
                    <p><br /><br /></p>
                    <p>&bull; Repeatedly utilizing reactions or different communications as a strategy for advancement or showcasing</p>
                    <p><br /><br /></p>
                    <p>&bull; Participating in abundance missions or units to misleadingly expand rankings for posts, records, organizations, or items</p>
                    <p><br /><br /></p>
                    <p>&bull; Use or re-utilize content layouts with slight changes across numerous posts and records</p>
                    <p>For every one of these practices, when we talk about "content," we mean posts as well as whatever other component that permits you to add your own content. At the point when we talk about "connections," we mean any element that permits one client to communicate with someone else or post.</p>
                    <p><br /><br /></p>
                    <p>We don't permit beguiling behavior on Blogry. This incorporates:</p>
                    <p><br /><br /></p>
                    <p>&bull; Posting content or mimicking an individual or association in a manner liable to bamboozle individuals. Farce and parody are fine, however clarify that is the thing that you're doing.</p>
                    <p><br /><br /></p>
                    <p>&bull; Using Blogry for phishing or misrepresentation. Try not to utilize labels, connections, titles, or other metadata in a deceptive way. Try not to connection to or implant malevolent or destructive code or programming in your posts</p>
                    <p>&bull;Don't use trickery to produce income or traffic</p>
                    <p>&bull;If you have gotten free merchandise or administrations, or anything of significant worth regarding the subject of a post, you should make this understood.</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <p><strong>Ads, Promotions, and Marketing</strong></p>
                    <ul>
                    <li>
                    <p>Third-party promoting and sponsorships are not permitted. While you may advance your own business, you may not publicize or advance outsider items, administrations, or brands through Blogry posts, distributions, or letters. This incorporates pictures that show brand sponsorship in a post or letter, or as a component of a distribution name or logo.</p>
                    </li>
                    <li>
                    <p>Images working as outsider promotions are not permitted. Inline pictures or implants that connection out and work as flag promotions for outsider brands are not permitted.</p>
                    </li>
                    <li>
                    <p>You should reveal partner joins. Associate connections, for example, interface out to Amazon with your code, or some other connection out where you will get a commission or other worth, are permitted in posts. Yet, you should uncover some place in the post that it incorporates member joins. On the off chance that you have gotten installment, products or administrations, or something different of worth in return for composing a post, you should in any case unveil this reality recorded as a hard copy inside your post.</p>
                    </li>
                    </ul>
                    <p>&nbsp;</p>
                    <p><strong>Embedded Content and Collection of Personal Information</strong><strong><br /></strong>To ensure the data privacy and security of our users, embedded content must comply with the following requirements. An &ldquo;embed&rdquo; includes a link, form, or a request for information or other content.</p>
                    <p>Embeds directly collecting data through Blogry form fields, comments or other onsite means are not allowed. This includes embeds that facilitate the submission of email addresses, credit card information or other personal information. If you want to collect information from your readers, you will need to follow these requirements:</p>
                    <ul>
                    <li>
                    <p>If you link out from your post on Blogry to a form hosted elsewhere, that form must make it clear to a user that they are no longer in the Blogry network and the information they disclose is subject to the third-party&rsquo;s Terms of Use and Privacy Policy,</p>
                    </li>
                    <li>
                    <p>If the link directs users to your own platform to subscribe to your newsletter, blog or other content you create, then in your Blogry content immediately next to the link you must disclose that the link will take the user offsite outside of Blogry</p>
                    </li>
                    <li>
                    <p>If your content includes a form that sends user information to you or a third-party, immediately next to or within the form you must disclose that the form will send the user&rsquo;s information to an offsite third-party outside of Blogry that is subject to that offsite third-party&rsquo;s Terms of Use and Privacy Policies, or offsite outside of Blogry, to you directly.</p>
                    </li>
                    </ul>
                    <p><strong>Crypto currency Accounts, Posts, and Publications</strong><strong><br /></strong></p>
                    <p>Posts and accounts that focus on crypto currencies which do not meet the following requirements may be considered spam and are subject to suspension, depending on context. Blogry does not endorse or verify any coin, token, or similar announcement.</p>
                    <p><strong>To prevent fraud and abuse, you must:</strong></p>
                    <ul>
                    <li>
                    <p>Include a link to your active project domain in your user account bio.</p>
                    </li>
                    <li>
                    <p>Use an email address from that domain as your verified Blogry account email, and maintain that email account actively.</p>
                    </li>
                    <li>
                    <p>Link at least one consistently-branded social media account (Facebook or Twitter) to your Blogry account. That social account should also link out prominently to the same domain as is included in your Blogry user bio.</p>
                    </li>
                    <li>
                    <p>Include a prominent about page with up-to-date contact information on your project website.</p>
                    </li>
                    </ul>
                    <p><strong>You may not:</strong></p>
                    <ul>
                    <li>
                    <p>Use an anonymous email address which is not linked to your project domain (e.g., gmail, protonmail, mail.ru, etc.)</p>
                    </li>
                    <li>
                    <p>Advertise or participate in bounty campaigns, pump and dumps, reviewing for reward, or other forms of brigading or inauthentic activity</p>
                    </li>
                    <li>
                    <p>Include shortened URLs in your posts</p>
                    </li>
                    </ul>
                    <p><strong>Paid, automatic, bulk, or non-genuine interactions</strong><strong><br /></strong>Blogry depends on various user behaviors &mdash; like views, clicks &mdash; to determine what content to feature and make the site work well for everyone. We don&rsquo;t allow artificial behaviors that skew this system and as a result degrade or distort other users&rsquo; experiences.</p>
                    <p>This includes:</p>
                    <ul>
                    <li>
                    <p>Buying, selling, or trading in accounts or account interactions &mdash; including views, clicks, likes, comments or other traffic</p>
                    </li>
                    <li>
                    <p>Using services, apps, or arrangements that offer you more views, clicks, likes, comments or other interactions on your Blogry account or content</p>
                    </li>
                    <li>
                    <p>Registering accounts, posting content, or interacting with users or content automatically, systematically, or programmatically</p>
                    </li>
                    </ul>
                    <p><strong>General Use of the Services</strong></p>
                    <p>You may not do, try to do, or cause a third party to do the following:<br />(1) access or tamper with non-public areas of the Services, our computer systems, or the systems of our technical providers;<br />(2) access or search the Services by any means other than the currently available, published interfaces (e.g., APIs) that we provide;<br />(3) forge any TCP/IP packet header or any part of the header information in any email or posting, or in any way use the Services to send altered, deceptive, or false source-identifying information;<br />(4) interfere with, or disrupt, the access of any user, host, or network, including sending a virus, overloading, flooding, spamming, mail-bombing the Services, scraping, or by scripting the creation of content or accounts in such a manner as to interfere with or create an undue burden on the Services</p>`;
}
